name: Release stage

on:
  workflow_call:
    inputs:
      image:
        type: string
        required: true
        description: "Container image including CI tooling"
      dry_run:
        type: boolean
        default: false
    outputs:
      new_version:
        description: "The version number generated"
        value: ${{ jobs.semantic_release.outputs.new_version }}
      released:
        description: "Whether a release was created"
        value: ${{ jobs.semantic_release.outputs.released }}

jobs:
  semantic_release:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      new_version: ${{ steps.set-output.outputs.version }}
      released: ${{ steps.set-output.outputs.released }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    # ONLY needed for PRs to fix the Detached HEAD error for python-semantic release
    - name: Attach to Branch (Fix Detached HEAD)
      if: github.event_name == 'pull_request'
      run: |
        git config --global --add safe.directory .
        git checkout -B ${{ github.head_ref }}
    - name: Release | semantic_release
      id: semantic_release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global --add safe.directory .

        NOOP_FLAG=""
        if [ "${{ inputs.dry_run }}" == "true" ]; then
          NOOP_FLAG="--noop"
        fi

        LAST_VERSION=$(semantic-release version --print-last-released)
        NEXT_VERSION=$(semantic-release version --print)

        echo "LAST_VERSION=$LAST_VERSION" >> $GITHUB_ENV
        echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV

        semantic-release $NOOP_FLAG -v version
    - name: Release | set-sematic_release-outputs
      id: set-output
      run: |
        if [ "$LAST_VERSION" != "$NEXT_VERSION" ] && [ "${{ inputs.dry_run }}" != "true" ]; then
          echo "🚀 A new version was created: $NEXT_VERSION"
          echo "version=$NEXT_VERSION" >> $GITHUB_OUTPUT
          echo "released=true" >> $GITHUB_OUTPUT
        else
          echo "💤 No release needed. Version remains: $LAST_VERSION"
          echo "released=false" >> $GITHUB_OUTPUT
        fi
    - name: Release | upload-build-asset
      id: upload-build-asset
      uses: actions/upload-artifact@v4
      if: always() && steps.semantic_release.outcome != 'skipped' && steps.set-output.outputs.released == 'true'
      with:
        name: build-asset
        path: "*.tar.gz"
        if-no-files-found: error