name: Secrets stage

on:
  workflow_call:
        
jobs:
  secret-detection:
    runs-on: ubuntu-latest

    steps:
      - name: Parse reference
        id: parse
        run: |
            # Extracts the @tag or @branch from the workflow_ref
            REF=$(echo "${{ github.workflow_ref }}" | awk -F '@' '{print $2}')
            echo "ref=$REF" >> $GITHUB_OUTPUT

      - name: Checkout Shared Repo
        uses: actions/checkout@v4
        with:
          repository: open-appdev-lab/ansible-collections-ci
          ref: ${{ steps.parse.outputs.shared_ref }}
          path: .shared

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important: Gitleaks needs history to scan commits
  
      - name: Run stage
        id: secret_detection
        uses: ./.shared/.github/actions/secret-detection

    # - name: Secrets | secret_detection (1/2)
    #   id: secret_detection
    #   uses: open-appdev-lab/ansible-collections-ci/.github/actions/secret-detection@0.1.0

      - name: Secrets | secret_detection (2/2)
        uses: actions/upload-artifact@v4
        if: always() && steps.secret_detection.outcome != 'skipped'
        with:
          name: secret_detection
          path: secret-detection-report.json
          if-no-files-found: error