name: CI for Ansible Collections

on:
  workflow_call:

concurrency:
  # Group by the branch/ref name. 
  # This ensures PRs don't block Main, and Main merges run one-by-one.
  group: ${{ github.workflow }}-${{ github.ref }}
  # For main branch, we set this to false to ensure releases finish.
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

  # default: least privileged permissions across all jobs
permissions:
  contents: read
  packages: read

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    outputs:
      shared_ref: ${{ steps.parse.outputs.ref }}
      image_tag: "ghcr.io/${{ github.repository }}/ci-python-env:${{ steps.parse.outputs.ref }}"
    steps:
      - id: parse
        run: |
          # Extracts the @tag or @branch from the workflow_ref
          REF=$(echo "${{ github.workflow_ref }}" | awk -F '@' '{print $2}')
          echo "ref=$REF" >> $GITHUB_OUTPUT

  secrets:
    needs: setup-environment
    uses: open-appdev-lab/ansible-collections-ci/.github/workflows/_secrets-stage.yml@v1.0.9

  prepare:
    needs: [ setup-environment, secrets ]
    uses: open-appdev-lab/ansible-collections-ci/.github/workflows/_prepare-stage.yml@v1.0.8
    with:
      image: ${{ needs.setup-environment.outputs.image_tag }}
    secrets:
      automation_hub_token: ${{ secrets.AUTOMATION_HUB_TOKEN }}

  test:
    needs: [ setup-environment, prepare ]
    uses: open-appdev-lab/ansible-collections-ci/.github/workflows/_test-stage.yml@v1.0.8
    with:
      image: ${{ needs.setup-environment.outputs.image_tag }}

  report:
    needs: [ setup-environment, test ]
    uses: open-appdev-lab/ansible-collections-ci/.github/workflows/_report-stage.yml@v1.0.8
    with:
      image: ${{ needs.setup-environment.outputs.image_tag }}

  release:
    permissions:
      contents: write
      packages: read
    if: github.ref == 'refs/heads/main'
    needs: [ setup-environment, report ]
    uses: open-appdev-lab/ansible-collections-ci/.github/workflows/_release-stage.yml@v1.0.8
    with:
      image: ${{ needs.setup-environment.outputs.image_tag }}
      dry_run: ${{ github.event_name == 'pull_request' }}

  publish:
    permissions:
      contents: write
      packages: read
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.release.outputs.released == 'true'
    needs: [ setup-environment, release ]
    uses: open-appdev-lab/ansible-collections-ci/.github/workflows/_publish-stage.yml@v1.0.8
    with:
      image: ${{ needs.setup-environment.outputs.image_tag }}
      tag_name: ${{ needs.release.outputs.new_version }}
    secrets:
      automation_hub_token: ${{ secrets.AUTOMATION_HUB_TOKEN }}
