name: CI workflow for releasing and publishing of Ansible collections

on:
  workflow_call:
    inputs:
      target_branch:
        type: string
        required: false
        default: "main"
        description: "The primary branch used for releases (e.g., main or master)"
      image:
        type: string
        required: false
        default: "ghcr.io/redhat-cop/openshift_virtualization_migration_ci/ci-python-env:latest"
        description: "Container image including CI tooling"
      test_requirements:
        type: string
        required: false
        default: "test-requirements.txt"
        description: "Python packages required for testing"
      ansible_requirements:
        type: string
        required: false
        default: "requirements-dev.yml"
        description: "Ansible collections dependencies"
      tox_config_file:
        type: string
        required: false
        default: "tox-ansible.ini"
        description: "Tox Ansible configuration file"
      automation_hub_url:
        type: string
        required: false
        default: 'https://console.redhat.com/api/automation-hub/'
        description: 'The API URL for the Automation Hub'
      publish_to_automation_hub:
        type: boolean
        required: false
        default: false
        description: 'Whether to publish the collection to the Automation Hub'
    secrets:
      automation_hub_token:
        required: true
        description: 'The Authentication Token for the Automation Hub'

concurrency:
  # Group by the branch/ref name. 
  # This ensures PRs don't block Main, and Main merges run one-by-one.
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.target_branch }}
  # For main branch, we set this to false to ensure releases finish.
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

# default: least privileged permissions across all jobs
permissions:
  contents: read
  packages: read

jobs:
  secrets:
    uses: redhat-cop/openshift_virtualization_migration_ci/.github/workflows/_secrets-stage.yml@main

  prepare:
    needs: secrets 
    uses: redhat-cop/openshift_virtualization_migration_ci/.github/workflows/_prepare-stage.yml@main
    with:
      image: ${{ inputs.image }}
      ansible_requirements: ${{ inputs.ansible_requirements }}
      automation_hub_url: ${{ inputs.automation_hub_url }}
    secrets:
      automation_hub_token: ${{ secrets.automation_hub_token }}

  test:
    needs: prepare
    uses: redhat-cop/openshift_virtualization_migration_ci/.github/workflows/_test-stage.yml@main
    with:
      image: ${{ inputs.image }}
      test_requirements: ${{ inputs.test_requirements}}
      tox_config_file: ${{ inputs.tox_config_file }}
      automation_hub_url: ${{ inputs.automation_hub_url }}
      lint_profile: "production"
      lint_strict: true
      lint_sarif_file: true
    secrets:
      automation_hub_token: ${{ secrets.automation_hub_token }}

  report:
    needs: test
    uses: redhat-cop/openshift_virtualization_migration_ci/.github/workflows/_report-stage.yml@main
    with:
      image: ${{ inputs.image }}

  release:
    if: |
      github.ref == format('refs/heads/{0}', inputs.target_branch) || 
      (github.event_name == 'pull_request' && github.base_ref == inputs.target_branch)
    needs: report
    uses: redhat-cop/openshift_virtualization_migration_ci/.github/workflows/_release-stage.yml@main
    permissions:
      contents: write
      packages: read
    with:
      image: ${{ inputs.image }}
      dry_run: ${{ github.event_name == 'pull_request' }}

  publish:
    if: |
      github.event_name == 'push' && 
      github.ref == format('refs/heads/{0}', inputs.target_branch) && 
      needs.release.outputs.released == 'true'
    needs: release
    uses: redhat-cop/openshift_virtualization_migration_ci/.github/workflows/_publish-stage.yml@main
    permissions:
      contents: write
      packages: read
    with:
      image: ${{ inputs.image }}
      tag_name: ${{ needs.release.outputs.new_version }}
      publish_to_automation_hub: ${{ inputs.publish_to_automation_hub }}
      automation_hub_url: ${{ inputs.automation_hub_url }}
    secrets:
      automation_hub_token: ${{ secrets.automation_hub_token }}
