name: demo

on:
  workflow_call:
jobs:
  docker-job:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v4

      - name: Run Docker Action
        id: my-docker
        uses: open-appdev-lab/ansible-collections-ci/.github/actions/dummy-container-task@beta
        with:
          who-to-greet: 'Container User'

      - name: View Output
        run: echo "The container used memory ${{ steps.my-docker.outputs.memory }}"